# Header
menu:
  # 首页: /
  # 历史: /archives
# rss: /atom.xml

# Content
excerpt_link: 更多
fancybox: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
